SELECT 
/*REPLACE BEGIN FOR DISTINCT*/
	FICHE_ID=				CAST(FICHE_ID AS VARCHAR)
	,DOCUMENT_NO
	,DATE_=					G3B.TDATE
	,BRANCH=				(SELECT MM.LogoBranch FROM Bms_126_MarkeRGeniusIntegration_Mapping MM where PosBranch=FK_STORE)
	,CUSTOMER_CODE=			CASE WHEN CUSTOMER_CODE='' THEN (SELECT TOP 1 DD.Value FROM Bms_126_MarkeRGeniusIntegration_Default DD WHERE DD.Description='YAZARKARA FISLI CARI BOS LOGO CARISI') ELSE CUSTOMER_CODE END
	,CUSTOMER_NAME
	,POS=					FK_POS
	,FTYPE
	/*,PTYPE*/
	,SALESMAN=				SALESMAN/*STLINEDA OLACAK*/
	,ITEMCODE=				ISNULL(ITM.CODE, G3B.BARCODE)
	,ITEMNAME=				ITM.NAME 
	,ITEMUNIT=				ISNULL((SELECT UL.CODE FROM LG_126_UNITSETL UL WHERE UL.MAINUNIT=1 AND UL.UNITSETREF=(SELECT TOP 1 I.UNITSETREF FROM LG_126_ITEMS I WITH(NOLOCK) WHERE I.CODE=ITM.CODE)), 'ADET')
	,QUANTITY=				G3B.QUANTITY
	,PRICE=					G3B.PRICE
	,LINETOTAL=				G3B.TOTALPRICE
	,LINE_DISCOUNT_TOTAL=	LINE_TOTL_DISCOUNT
	,DISCOUNT_TOTAL,INDIRECT_DISCOUNT_TOTAL,CAMPAIGN_DISCOUNT,CHEQUE_DISCOUNT
	/*select * from [[BMSF_126_PennaGenius_Sales_WithCustomer]]('12/26/2023 00:00:00','12/26/2023 23:59:59') where LINE_TOTL_DISCOUNT<>0*/
/*REPLACE END FOR DISTINCT*/
FROM
	LG_126_UNITBARCODE AS UBR RIGHT OUTER JOIN
	(
SELECT FICHE_ID,FTYPE='SATIS',TDATE,FK_STORE,DOCUMENT_NO,CUSTOMER_CODE,CUSTOMER_NAME,FK_POS,SALESMAN,BARCODE,SUM(QUANTITY) AS QUANTITY,AVG(PRICE) AS PRICE,SUM(TOTALPRICE) AS TOTALPRICE,SUM(LINE_TOTL_DISCOUNT) AS LINE_TOTL_DISCOUNT,
SUM(DISCOUNT_TOTAL) DISCOUNT_TOTAL,SUM(INDIRECT_DISCOUNT_TOTAL) INDIRECT_DISCOUNT_TOTAL,SUM(CAMPAIGN_DISCOUNT) CAMPAIGN_DISCOUNT,SUM(CHEQUE_DISCOUNT) CHEQUE_DISCOUNT,
SUM(LINE_TOTAL_VAT) AS LINE_TOTAL_VAT FROM (
SELECT 
	FICHE_ID=TRANSACTION_HEADER.ID,
	FTYPE='SATIS',
	/*PTYPE=(SELECT PT.DESCRIPTION FROM [192.168.3.197].[Genius3].[GENIUS3].PAYMENT_TYPE PT WITH(NOLOCK) WHERE PT.ID=(SELECT top 1  TP.FK_PAYMENT_TYPE FROM [192.168.3.197].[Genius3].[GENIUS3].TRANSACTION_PAYMENT TP WITH(NOLOCK) WHERE TRANSACTION_HEADER.ID=TP.FK_TRANSACTION_HEADER)),*/
	cast(TRANS_DATE as date) AS TDATE,FK_STORE,
	DOCUMENT_NO,CUSTOMER_CODE=TRANSACTION_HEADER.CUSTOMER_CODE,CUSTOMER_NAME=TRANSACTION_HEADER.NAME_ON_DOC,
    FK_POS=(SELECT PPOS.NUM FROM [192.168.3.197].[Genius3].[GENIUS3].POS PPOS WITH(NOLOCK)  WHERE PPOS.ID=FK_POS)
	,SALESMAN=(SELECT GUT.CODE FROM [192.168.3.197].[Genius3].[GENIUS3].[USERS] GUT WITH(NOLOCK)  WHERE GUT.ID=FK_USER)
	,BARCODE, SUM(AMOUNT) AS QUANTITY, AVG(UNIT_PRICE) AS PRICE, 
                      SUM(TOTAL_PRICE - (DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT)) AS TOTALPRICE, 
                      SUM(DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT) AS LINE_TOTL_DISCOUNT					  
					  ,SUM(DISCOUNT_TOTAL) DISCOUNT_TOTAL
					  ,SUM(INDIRECT_DISCOUNT_TOTAL) INDIRECT_DISCOUNT_TOTAL
					  ,SUM(CAMPAIGN_DISCOUNT) CAMPAIGN_DISCOUNT
					  ,SUM(CHEQUE_DISCOUNT) CHEQUE_DISCOUNT
					  ,SUM(VAT_TOTAL) AS LINE_TOTAL_VAT
FROM         [192.168.3.197].Genius3.GENIUS3.TRANSACTION_SALE WITH(NOLOCK)  INNER JOIN
                      [192.168.3.197].Genius3.GENIUS3.TRANSACTION_HEADER WITH(NOLOCK)  ON TRANSACTION_SALE.FK_TRANSACTION_HEADER = TRANSACTION_HEADER.ID
WHERE     ((/* satislar	*/ TRANSACTION_HEADER.PTYPE NOT IN (2, 6) AND TRANSACTION_SALE.STATUS = 0 AND TRANSACTION_HEADER.STATUS = 0) OR
                      (/* iade satis iptali */ TRANSACTION_HEADER.PTYPE IN (2, 6) AND TRANSACTION_SALE.STATUS = 1 AND TRANSACTION_HEADER.STATUS = 0)) AND 
                      TRANSACTION_HEADER.TRANS_DATE BETWEEN @DATE1 AND @DATE2 AND (TRANSACTION_HEADER.CUSTOMER_CODE <>'' OR TRANSACTION_HEADER.DOCUMENT_NO<>'')
GROUP BY cast(TRANS_DATE as date),FK_STORE,FK_POS,FK_USER, BARCODE,DOCUMENT_NO, TRANSACTION_HEADER.CUSTOMER_CODE, TRANSACTION_HEADER.NAME_ON_DOC, TRANSACTION_HEADER.ID
/* satir iptalleri ve iadeleri cikartmak*/ UNION ALL
/*IPTAL*/
SELECT   
	FICHE_ID=TRANSACTION_HEADER.ID,
	FTYPE='SATIRIPTAL',
	/*PTYPE=(SELECT PT.DESCRIPTION FROM [192.168.3.197].[Genius3].[GENIUS3].PAYMENT_TYPE PT WITH(NOLOCK) WHERE PT.ID=(SELECT top 1  TP.FK_PAYMENT_TYPE FROM [192.168.3.197].[Genius3].[GENIUS3].TRANSACTION_PAYMENT TP WITH(NOLOCK) WHERE TRANSACTION_HEADER.ID=TP.FK_TRANSACTION_HEADER)),*/
	cast(TRANS_DATE as date) AS TDATE,FK_STORE,
	DOCUMENT_NO,CUSTOMER_CODE=TRANSACTION_HEADER.CUSTOMER_CODE,CUSTOMER_NAME=TRANSACTION_HEADER.NAME_ON_DOC,
	FK_POS=(SELECT PPOS.NUM FROM [192.168.3.197].[Genius3].[GENIUS3].POS PPOS WITH(NOLOCK)  WHERE PPOS.ID=FK_POS)
	,SALESMAN=(SELECT GUT.CODE FROM [192.168.3.197].[Genius3].[GENIUS3].[USERS] GUT WITH(NOLOCK)  WHERE GUT.ID=FK_USER)
	,BARCODE, - SUM(AMOUNT) AS QUANTITY, AVG(UNIT_PRICE) AS PRICE, 
                      - SUM(TOTAL_PRICE - (DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT)) AS TOTALPRICE, 
                      - SUM(DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT) AS LINE_TOTL_DISCOUNT					  
					  ,-SUM(DISCOUNT_TOTAL) DISCOUNT_TOTAL
					  ,-SUM(INDIRECT_DISCOUNT_TOTAL) INDIRECT_DISCOUNT_TOTAL
					  ,-SUM(CAMPAIGN_DISCOUNT) CAMPAIGN_DISCOUNT
					  ,-SUM(CHEQUE_DISCOUNT) CHEQUE_DISCOUNT
					  ,SUM(VAT_TOTAL) AS LINE_TOTAL_VAT
FROM         [192.168.3.197].Genius3.GENIUS3.TRANSACTION_SALE  WITH(NOLOCK) INNER JOIN
                      [192.168.3.197].Genius3.GENIUS3.TRANSACTION_HEADER  WITH(NOLOCK) ON TRANSACTION_SALE.FK_TRANSACTION_HEADER = TRANSACTION_HEADER.ID
WHERE     (/* iptal edilen satirlar	*/ TRANSACTION_HEADER.PTYPE NOT IN (2, 6) AND TRANSACTION_SALE.STATUS = 1 AND TRANSACTION_HEADER.STATUS = 0) AND
                      TRANSACTION_HEADER.TRANS_DATE BETWEEN @DATE1 AND @DATE2 AND (TRANSACTION_HEADER.CUSTOMER_CODE <>'' OR TRANSACTION_HEADER.DOCUMENT_NO<>'')
GROUP BY cast(TRANS_DATE as date),FK_STORE,FK_POS,FK_USER, BARCODE,DOCUMENT_NO, TRANSACTION_HEADER.CUSTOMER_CODE, TRANSACTION_HEADER.NAME_ON_DOC, TRANSACTION_HEADER.ID
) AS SATISVESATIRIPTAL GROUP BY FK_STORE,FK_POS,SALESMAN,TDATE,BARCODE ,DOCUMENT_NO,CUSTOMER_CODE,CUSTOMER_NAME, FICHE_ID
UNION ALL
/*IADE*/
SELECT     
	FICHE_ID=TRANSACTION_HEADER.ID,
	FTYPE='IADE',
	/*PTYPE=(SELECT PT.DESCRIPTION FROM [192.168.3.197].[Genius3].[GENIUS3].PAYMENT_TYPE PT WITH(NOLOCK) WHERE PT.ID=(SELECT top 1  TP.FK_PAYMENT_TYPE FROM [192.168.3.197].[Genius3].[GENIUS3].TRANSACTION_PAYMENT TP WITH(NOLOCK) WHERE TRANSACTION_HEADER.ID=TP.FK_TRANSACTION_HEADER)),*/
	cast(TRANS_DATE as date) AS TDATE,FK_STORE,
	DOCUMENT_NO,CUSTOMER_CODE=TRANSACTION_HEADER.CUSTOMER_CODE,CUSTOMER_NAME=TRANSACTION_HEADER.NAME_ON_DOC,
	FK_POS=(SELECT PPOS.NUM FROM [192.168.3.197].[Genius3].[GENIUS3].POS PPOS WITH(NOLOCK)  WHERE PPOS.ID=FK_POS)
	,SALESMAN=(SELECT GUT.CODE FROM [192.168.3.197].[Genius3].[GENIUS3].[USERS] GUT  WITH(NOLOCK) WHERE GUT.ID=FK_USER)
	,BARCODE,  SUM(AMOUNT) AS QUANTITY, AVG(UNIT_PRICE) AS PRICE, 
                       SUM(TOTAL_PRICE - (DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT)) AS TOTALPRICE, 
                       SUM(DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT) AS LINE_TOTL_DISCOUNT					  
					  ,SUM(DISCOUNT_TOTAL) DISCOUNT_TOTAL
					  ,SUM(INDIRECT_DISCOUNT_TOTAL) INDIRECT_DISCOUNT_TOTAL
					  ,SUM(CAMPAIGN_DISCOUNT) CAMPAIGN_DISCOUNT
					  ,SUM(CHEQUE_DISCOUNT) CHEQUE_DISCOUNT
					  ,SUM(VAT_TOTAL) AS LINE_TOTAL_VAT
FROM         [192.168.3.197].Genius3.GENIUS3.TRANSACTION_SALE WITH(NOLOCK)  INNER JOIN
                      [192.168.3.197].Genius3.GENIUS3.TRANSACTION_HEADER WITH(NOLOCK)  ON TRANSACTION_SALE.FK_TRANSACTION_HEADER = TRANSACTION_HEADER.ID
WHERE     (/* iadeler*/ TRANSACTION_HEADER.PTYPE IN (2, 6) AND TRANSACTION_SALE.STATUS = 0 AND TRANSACTION_HEADER.STATUS = 0) AND 
                      TRANSACTION_HEADER.TRANS_DATE BETWEEN @DATE1 AND @DATE2 AND (TRANSACTION_HEADER.CUSTOMER_CODE <>'' OR TRANSACTION_HEADER.DOCUMENT_NO<>'')
GROUP BY cast(TRANS_DATE as date),FK_STORE,FK_POS,FK_USER, BARCODE,DOCUMENT_NO,  TRANSACTION_HEADER.CUSTOMER_CODE, TRANSACTION_HEADER.NAME_ON_DOC, TRANSACTION_HEADER.ID
	) AS G3B ON UBR.BARCODE = G3B.BARCODE LEFT OUTER JOIN
	LG_126_ITEMS ITM  ON ITM.LOGICALREF=UBR.ITEMREF
WHERE 
	--FK_STORE IN ('10001','10002','10003')
	1=1 /*AND FK_STORE='9999999'carisiz atmak için testler 9999999 silesrsen alır*/