SELECT 
/*REPLACE BEGIN FOR DISTINCT*/
	DATE_=					G3B.TDATE
	,BRANCH=				(SELECT MM.LogoBranch FROM Bms_126_MarkeRGeniusIntegration_Mapping MM where PosBranch=FK_STORE)/*CASE FK_STORE WHEN '10001' THEN '0' WHEN '10002' THEN '2' WHEN '10003' THEN '1' END*/
	,POS=					FK_POS
	,FTYPE
	,SALESMAN=				SALESMAN/*STLINEDA OLACAK*/
	,ITEMCODE=				ISNULL(ITM.CODE, G3B.BARCODE)
	,ITEMNAME=				ITM.NAME 
	,ITEMUNIT=				ISNULL((SELECT UL.CODE FROM LG_126_UNITSETL UL WHERE UL.MAINUNIT=1 AND UL.UNITSETREF=(SELECT TOP 1 I.UNITSETREF FROM LG_126_ITEMS I WITH(NOLOCK) WHERE I.CODE=ITM.CODE)), 'ADET')
	,QUANTITY=				G3B.QUANTITY
	,PRICE=					G3B.PRICE
	,LINETOTAL=				G3B.TOTALPRICE
	,LINE_DISCOUNT_TOTAL=	LINE_TOTL_DISCOUNT
	,DISCOUNT_TOTAL,INDIRECT_DISCOUNT_TOTAL,CAMPAIGN_DISCOUNT,CHEQUE_DISCOUNT
	/*select * from [BMSF_126_ErulkuGenius_Sales]('12/26/2023 00:00:00','12/26/2023 23:59:59') where LINE_TOTL_DISCOUNT<>0*/
/*REPLACE END FOR DISTINCT*/
FROM
	LG_126_UNITBARCODE AS UBR RIGHT OUTER JOIN
	(
SELECT FTYPE='SATIS',TDATE,FK_STORE,FK_POS,SALESMAN,BARCODE,SUM(QUANTITY) AS QUANTITY,AVG(PRICE) AS PRICE,SUM(TOTALPRICE) AS TOTALPRICE,SUM(LINE_TOTL_DISCOUNT) AS LINE_TOTL_DISCOUNT,
SUM(DISCOUNT_TOTAL) DISCOUNT_TOTAL,SUM(INDIRECT_DISCOUNT_TOTAL) INDIRECT_DISCOUNT_TOTAL,SUM(CAMPAIGN_DISCOUNT) CAMPAIGN_DISCOUNT,SUM(CHEQUE_DISCOUNT) CHEQUE_DISCOUNT,
SUM(LINE_TOTAL_VAT) AS LINE_TOTAL_VAT FROM (
SELECT FTYPE='SATIS',  cast(TRANS_DATE as date) AS TDATE,FK_STORE,
    FK_POS=(SELECT PPOS.NUM FROM [192.168.3.197].[Genius3].[GENIUS3].POS PPOS WHERE PPOS.ID=FK_POS)
	,SALESMAN=(SELECT GUT.CODE FROM [192.168.3.197].[Genius3].[GENIUS3].[USERS] GUT WHERE GUT.ID=FK_USER)
	,BARCODE, SUM(AMOUNT) AS QUANTITY, AVG(UNIT_PRICE) AS PRICE, 
                      SUM(TOTAL_PRICE - (DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT)) AS TOTALPRICE, 
                      SUM(DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT) AS LINE_TOTL_DISCOUNT					  
					  ,SUM(DISCOUNT_TOTAL) DISCOUNT_TOTAL
					  ,SUM(INDIRECT_DISCOUNT_TOTAL) INDIRECT_DISCOUNT_TOTAL
					  ,SUM(CAMPAIGN_DISCOUNT) CAMPAIGN_DISCOUNT
					  ,SUM(CHEQUE_DISCOUNT) CHEQUE_DISCOUNT
					  ,SUM(VAT_TOTAL) AS LINE_TOTAL_VAT
FROM         [192.168.3.197].Genius3.GENIUS3.TRANSACTION_SALE INNER JOIN
                      [192.168.3.197].Genius3.GENIUS3.TRANSACTION_HEADER ON TRANSACTION_SALE.FK_TRANSACTION_HEADER = TRANSACTION_HEADER.ID
WHERE     ((/* satislar	*/ TRANSACTION_HEADER.PTYPE NOT IN (2, 6) AND TRANSACTION_SALE.STATUS = 0 AND TRANSACTION_HEADER.STATUS = 0) OR
                      (/* iade satis iptali */ TRANSACTION_HEADER.PTYPE IN (2, 6) AND TRANSACTION_SALE.STATUS = 1 AND TRANSACTION_HEADER.STATUS = 0)) AND 
                      cast(TRANSACTION_HEADER.TRANS_DATE as date) BETWEEN '20241130' AND '20241130' /*AND TRANSACTION_HEADER.FK_CUSTOMER='0'*/
GROUP BY cast(TRANS_DATE as date),FK_STORE,FK_POS,FK_USER, BARCODE
/* satir iptalleri ve iadeleri cikartmak*/ UNION ALL
/*IPTAL*/
SELECT     
	FTYPE='SATIRIPTAL',cast(TRANS_DATE as date) AS TDATE,FK_STORE,
	FK_POS=(SELECT PPOS.NUM FROM [192.168.3.197].[Genius3].[GENIUS3].POS PPOS WHERE PPOS.ID=FK_POS)
	,SALESMAN=(SELECT GUT.CODE FROM [192.168.3.197].[Genius3].[GENIUS3].[USERS] GUT WHERE GUT.ID=FK_USER)
	,BARCODE, - SUM(AMOUNT) AS QUANTITY, AVG(UNIT_PRICE) AS PRICE, 
                      - SUM(TOTAL_PRICE - (DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT)) AS TOTALPRICE, 
                      - SUM(DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT) AS LINE_TOTL_DISCOUNT					  
					  ,-SUM(DISCOUNT_TOTAL) DISCOUNT_TOTAL
					  ,-SUM(INDIRECT_DISCOUNT_TOTAL) INDIRECT_DISCOUNT_TOTAL
					  ,-SUM(CAMPAIGN_DISCOUNT) CAMPAIGN_DISCOUNT
					  ,-SUM(CHEQUE_DISCOUNT) CHEQUE_DISCOUNT
					  ,SUM(VAT_TOTAL) AS LINE_TOTAL_VAT
FROM         [192.168.3.197].Genius3.GENIUS3.TRANSACTION_SALE INNER JOIN
                      [192.168.3.197].Genius3.GENIUS3.TRANSACTION_HEADER ON TRANSACTION_SALE.FK_TRANSACTION_HEADER = TRANSACTION_HEADER.ID
WHERE     (/* iptal edilen satirlar	*/ TRANSACTION_HEADER.PTYPE NOT IN (2, 6) AND TRANSACTION_SALE.STATUS = 1 AND TRANSACTION_HEADER.STATUS = 0) AND
                      cast(TRANSACTION_HEADER.TRANS_DATE as date) BETWEEN '20241130' AND '20241130' /*AND TRANSACTION_HEADER.FK_CUSTOMER='0'*/
GROUP BY cast(TRANS_DATE as date),FK_STORE,FK_POS,FK_USER, BARCODE
) AS SATISVESATIRIPTAL GROUP BY FK_STORE,FK_POS,SALESMAN,TDATE,BARCODE
UNION ALL
/*IADE*/
SELECT     FTYPE='IADE',cast(TRANS_DATE as date) AS TDATE,FK_STORE,
	FK_POS=(SELECT PPOS.NUM FROM [192.168.3.197].[Genius3].[GENIUS3].POS PPOS WHERE PPOS.ID=FK_POS)
	,SALESMAN=(SELECT GUT.CODE FROM [192.168.3.197].[Genius3].[GENIUS3].[USERS] GUT WHERE GUT.ID=FK_USER)
	,BARCODE,  SUM(AMOUNT) AS QUANTITY, AVG(UNIT_PRICE) AS PRICE, 
                       SUM(TOTAL_PRICE - (DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT)) AS TOTALPRICE, 
                       SUM(DISCOUNT_TOTAL + INDIRECT_DISCOUNT_TOTAL + CAMPAIGN_DISCOUNT + CHEQUE_DISCOUNT) AS LINE_TOTL_DISCOUNT					  
					  ,SUM(DISCOUNT_TOTAL) DISCOUNT_TOTAL
					  ,SUM(INDIRECT_DISCOUNT_TOTAL) INDIRECT_DISCOUNT_TOTAL
					  ,SUM(CAMPAIGN_DISCOUNT) CAMPAIGN_DISCOUNT
					  ,SUM(CHEQUE_DISCOUNT) CHEQUE_DISCOUNT
					  ,SUM(VAT_TOTAL) AS LINE_TOTAL_VAT
FROM         [192.168.3.197].Genius3.GENIUS3.TRANSACTION_SALE INNER JOIN
                      [192.168.3.197].Genius3.GENIUS3.TRANSACTION_HEADER ON TRANSACTION_SALE.FK_TRANSACTION_HEADER = TRANSACTION_HEADER.ID
WHERE     (/* iadeler*/ TRANSACTION_HEADER.PTYPE IN (2, 6) AND TRANSACTION_SALE.STATUS = 0 AND TRANSACTION_HEADER.STATUS = 0) AND 
                      cast(TRANSACTION_HEADER.TRANS_DATE as date) BETWEEN '20241130' AND '20241130' /*AND TRANSACTION_HEADER.FK_CUSTOMER='0'*/
GROUP BY cast(TRANS_DATE as date),FK_STORE,FK_POS,FK_USER, BARCODE	
	) AS G3B ON UBR.BARCODE = G3B.BARCODE LEFT OUTER JOIN
	LG_126_ITEMS ITM ON ITM.LOGICALREF=UBR.ITEMREF
WHERE 
	1=1