SELECT 
LOGO_BRANCH=(SELECT top 1 MM.LogoBranch FROM Bms_124_ErulkuGeniusIntegration_Mapping MM where MM.PosBranch=STORE)
,LOGO_FICHE_TYPE=(SELECT top 1 MM.LogoFicheType FROM Bms_124_ErulkuGeniusIntegration_PaymentMapping MM where MM.Saleman=TF.SALESMAN AND MM.IntegrationCode=TF.PAYMENT_TYPE) 
,LOGO_CURRENCY=(SELECT top 1 CASE MM.Currency WHEN 'USD' THEN '1' WHEN 'GBP' THEN '17' WHEN 'EUR' THEN '20' ELSE '0' END FROM Bms_124_ErulkuGeniusIntegration_PaymentMapping MM where MM.Saleman=TF.SALESMAN AND MM.IntegrationCode=TF.PAYMENT_TYPE) 
,LOGO_BANK_OR_KS_CODE=(SELECT top 1 MM.BankOrKsCode FROM Bms_124_ErulkuGeniusIntegration_PaymentMapping MM where MM.Saleman=TF.SALESMAN AND MM.IntegrationCode=TF.PAYMENT_TYPE) 
,* FROM (
	SELECT TOP 100 PERCENT
	/*PYM.FK_TRANSACTION_HEADER
	FK_STORE=(SELECT PPOS.NUM FROM [192.168.5.103].[Genius3].[GENIUS3].STORE PPOS WITH(NOLOCK)  WHERE PPOS.ID=TH.FK_STORE)
	,*/
	STORE=FK_STORE	
	,POS=(SELECT PPOS.NUM FROM [192.168.5.103].[Genius3].[GENIUS3].POS PPOS WITH(NOLOCK)  WHERE PPOS.ID=TH.FK_POS)
	,SALESMAN=(SELECT GUT.CODE FROM [192.168.5.103].[Genius3].[GENIUS3].[USERS] GUT WITH(NOLOCK)  WHERE GUT.ID=TH.FK_USER)
	,DATE_=CAST(TH.TRANS_DATE AS DATE)
	,CUSTOMER_CODE= case when TH.DOCUMENT_NO<>'' AND TH.CUSTOMER_CODE='' THEN (SELECT TOP 1 DD.Value FROM Bms_124_ErulkuGeniusIntegration_Default DD WHERE DD.Description='YAZARKARA FISLI CARI BOS LOGO CARISI') ELSE CUSTOMER_CODE END
	,CUSTOMER_NAME=TH.NAME_ON_DOC
	,TH.DOCUMENT_NO
	/*,PYM.PAYMENT_TYPE*/
	,PAYMENT_TYPE=PYM.FK_PAYMENT_TYPE
	,PAYMENT_TYPE_DESCRIPTION=(SELECT PT.DESCRIPTION FROM [192.168.5.103].Genius3.GENIUS3.PAYMENT_TYPE PT WHERE PT.ID=PYM.FK_PAYMENT_TYPE)
	,SERIAL_NO = ISNULL(PYM.SERIAL_NO,'')
	/*,CUSTOM_TEXT = CASE WHEN PYM.CUSTOM_TEXT = '6' THEN PYM.CUSTOM_TEXT ELSE '0' END*/
    ,PAYMENT_TOTAL = SUM(
        CASE
            WHEN PYM.[STATUS] = 0 THEN PYM.PAYMENT_TOTAL
            WHEN PYM.[STATUS] = 1 THEN -1 * PYM.PAYMENT_TOTAL
        END
     )
	from [192.168.5.103].Genius3.GENIUS3.TRANSACTION_PAYMENT PYM WITH(NOLOCK)
	LEFT JOIN [192.168.5.103].Genius3.GENIUS3.TRANSACTION_HEADER TH WITH(NOLOCK) ON TH.ID=PYM.FK_TRANSACTION_HEADER
	WHERE
		YEAR(TH.TRANS_DATE)=2024/*TH.TRANS_DATE BETWEEN @DATE1 AND @DATE2*/ AND TH.FK_STORE = (SELECT top 1 MM.PosBranch FROM Bms_124_ErulkuGeniusIntegration_Mapping MM where LogoBranch=0)  
    GROUP BY
           /*PYM.FK_TRANSACTION_HEADER,*/
           TH.FK_STORE,TH.FK_POS,TH.FK_USER,CAST(TH.TRANS_DATE AS DATE),TH.CUSTOMER_CODE,TH.NAME_ON_DOC,TH.DOCUMENT_NO,/*PYM.PAYMENT_TYPE ,*/PYM.FK_PAYMENT_TYPE ,PYM.SERIAL_NO/*,PYM.CUSTOM_TEXT*/
    HAVING SUM(
               CASE
                    WHEN PYM.[STATUS] = 0 THEN PYM.PAYMENT_TOTAL
                    WHEN PYM.[STATUS] = 1 THEN -1 * PYM.PAYMENT_TOTAL
               END
           ) > 0
    ORDER BY MIN(PYM.ID) ASC 
) AS TF
WHERE 1=2 AND (SELECT top 1 MM.LogoFicheType FROM Bms_124_ErulkuGeniusIntegration_PaymentMapping MM where MM.Saleman=TF.SALESMAN AND MM.IntegrationCode=TF.PAYMENT_TYPE) IS NOT NULL
	--  NAKİT TAHSİLATLAR KASADAN OLMAKTA KASA KODU KREDİ VE MERKEZ 
	--ERULKU ÇEK GİRİŞİ ÖRNEK BORDRO NO 1798
	
	--KASA NAKİT TAHSİLAT (ÖR 00365 66238,11), KASA NAKİT ÖDEME (ÖR 00020 3011,80), ÇEK GİRİŞİ (ör bordro no 15037 2000 BORDRO VE ÇEK ÖZEL KOD POSF, ÇEK PORTFOY NO E0001)
	
	--  KREDİ KARTI KASA ADI : KREDI , NAKIT KASA ADI : MERKEZ
	
	--ÇEK select SUM(PAYMENT_TOTAL) from GENIUS3.TRANSACTION_PAYMENT PYM WHERE SERIAL_NO<>'' AND FK_PAYMENT_TYPE=3 and PYM.PAYMENT_TYPE=0